### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by Reistha10** [Reistha10/Capstone_Project018#3]
- [ ] Mengumpulkan dataset
- [ ] Merancang desain Front End
- [ ] Membuat tampilan dasar website
- [ ] Membangun model sistem rekomendasi
- [ ] Melakukan training model
- [ ] Menambahkan isi dan fitur-fitur website
- [ ] Membuat berkas Javascript
- [ ] Melakukan Training model
- [ ] Melakukan uji coba model dengan data baru
- [ ] Menghubungkan model machine learning dengan website
- [ ] Memperbaiki tampilan website
- [ ] Men-deployment proyek
- [ ] Mengumpulkan Submission Proyek
